import { Pool, type PoolClient, type QueryResultRow } from "pg";
import menuSeedData from "@/data/menu-items.json";
import defaultAuth from "@/data/default-auth.json";

export type BusinessSettings = {
  restaurantName: string;
  address: string;
  phone: string;
  email: string;
  gstin: string;
  defaultGstRate: number;
  printerWidthMm: number;
  currencySymbol: string;
  timezone: string;
};

export type MenuItem = {
  id: number;
  productId: string;
  name: string;
  category: string;
  pricePaise: number;
  costPaise: number;
  isActive: boolean;
};

const seedItems = menuSeedData;

const schemaSql = `
CREATE TABLE IF NOT EXISTS menu_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  price_paise INTEGER NOT NULL CHECK(price_paise >= 0),
  cost_paise INTEGER NOT NULL DEFAULT 0 CHECK(cost_paise >= 0),
  is_active SMALLINT NOT NULL DEFAULT 1 CHECK(is_active IN (0,1)),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS bills (
  id TEXT PRIMARY KEY,
  bill_date TEXT NOT NULL,
  daily_number INTEGER NOT NULL,
  created_at TEXT NOT NULL,
  customer_name TEXT,
  customer_phone TEXT,
  payment_method TEXT NOT NULL,
  gst_enabled SMALLINT NOT NULL DEFAULT 0 CHECK(gst_enabled IN (0,1)),
  gst_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
  subtotal_paise INTEGER NOT NULL,
  cgst_paise INTEGER NOT NULL DEFAULT 0,
  sgst_paise INTEGER NOT NULL DEFAULT 0,
  total_paise INTEGER NOT NULL,
  cogs_paise INTEGER NOT NULL DEFAULT 0,
  UNIQUE(bill_date, daily_number)
);

CREATE TABLE IF NOT EXISTS bill_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bill_id TEXT NOT NULL REFERENCES bills(id) ON DELETE CASCADE,
  menu_item_id INTEGER,
  product_id TEXT NOT NULL,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  unit_price_paise INTEGER NOT NULL,
  unit_cost_paise INTEGER NOT NULL DEFAULT 0,
  quantity INTEGER NOT NULL CHECK(quantity > 0),
  line_total_paise INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_bills_date ON bills(bill_date);
CREATE INDEX IF NOT EXISTS idx_bill_items_bill ON bill_items(bill_id);

CREATE TABLE IF NOT EXISTS expenses (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  expense_date TEXT NOT NULL,
  amount_paise INTEGER NOT NULL CHECK(amount_paise > 0),
  note TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_expenses_date ON expenses(expense_date);

CREATE TABLE IF NOT EXISTS business_settings (
  id INTEGER PRIMARY KEY CHECK(id = 1),
  restaurant_name TEXT NOT NULL,
  address TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT NOT NULL,
  gstin TEXT NOT NULL,
  default_gst_rate DOUBLE PRECISION NOT NULL,
  printer_width_mm INTEGER NOT NULL,
  currency_symbol TEXT NOT NULL,
  timezone TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS daily_bill_counters (
  bill_date TEXT PRIMARY KEY,
  last_number INTEGER NOT NULL CHECK(last_number >= 0)
);

CREATE TABLE IF NOT EXISTS admin_credentials (
  id INTEGER PRIMARY KEY CHECK(id = 1),
  username TEXT NOT NULL UNIQUE,
  password_salt TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS menu_product_seq START WITH 1 INCREMENT BY 1;
`;

type GlobalDb = typeof globalThis & {
  __nutreePgPool?: Pool;
  __nutreePgInit?: Promise<void>;
};

const globalForDb = globalThis as GlobalDb;

export function getDbPool() {
  const connectionString = process.env.DATABASE_URL?.trim();
  if (!connectionString) {
    throw new Error(
      "DATABASE_URL is not configured. Add your PostgreSQL/Neon connection string to .env.local and Vercel Environment Variables.",
    );
  }

  if (!globalForDb.__nutreePgPool) {
    globalForDb.__nutreePgPool = new Pool({
      connectionString,
      max: 3,
      idleTimeoutMillis: 20_000,
      connectionTimeoutMillis: 10_000,
    });
  }

  return globalForDb.__nutreePgPool;
}

async function seedDefaultData(client: PoolClient) {
  const timezone = process.env.BUSINESS_TZ?.trim() || "Asia/Kolkata";

  await client.query(
    `
      INSERT INTO business_settings
        (id, restaurant_name, address, phone, email, gstin, default_gst_rate, printer_width_mm, currency_symbol, timezone)
      VALUES (1, $1, $2, $3, $4, $5, $6, $7, $8, $9)
      ON CONFLICT (id) DO NOTHING
    `,
    ["NutreeNext", "", "9758100102", "Contact@nutreenext.com", "", 5, 58, "₹", timezone],
  );

  const values: unknown[] = [];
  const placeholders = seedItems.map((item, index) => {
    const offset = index * 6;
    const now = new Date().toISOString();
    values.push(item.productId, item.name, item.category, item.priceRupees * 100, now, now);
    return `($${offset + 1}::text, $${offset + 2}::text, $${offset + 3}::text, $${offset + 4}::integer, 0::integer, 1::smallint, $${offset + 5}::text, $${offset + 6}::text)`;
  });

  await client.query(
    `
      INSERT INTO menu_items
        (product_id, name, category, price_paise, cost_paise, is_active, created_at, updated_at)
      SELECT seed.product_id, seed.name, seed.category, seed.price_paise, seed.cost_paise, seed.is_active, seed.created_at, seed.updated_at
      FROM (VALUES ${placeholders.join(",\n")})
        AS seed(product_id, name, category, price_paise, cost_paise, is_active, created_at, updated_at)
      WHERE NOT EXISTS (
        SELECT 1
        FROM menu_items existing
        WHERE LOWER(BTRIM(existing.name)) = LOWER(BTRIM(seed.name))
      )
      ON CONFLICT (product_id) DO NOTHING
    `,
    values,
  );

  await client.query(
    `
      INSERT INTO admin_credentials (id, username, password_salt, password_hash, updated_at)
      VALUES (1, $1, $2, $3, $4)
      ON CONFLICT (id) DO NOTHING
    `,
    [defaultAuth.username, defaultAuth.salt, defaultAuth.hash, new Date().toISOString()],
  );
}

export async function ensureDatabase() {
  if (globalForDb.__nutreePgInit) return globalForDb.__nutreePgInit;

  const initPromise = (async () => {
    const pool = getDbPool();
    const client = await pool.connect();
    try {
      await client.query("BEGIN");
      await client.query("SELECT pg_advisory_xact_lock(794331001)");
      await client.query(schemaSql);
      await seedDefaultData(client);
      await client.query("COMMIT");
    } catch (error) {
      await client.query("ROLLBACK");
      throw error;
    } finally {
      client.release();
    }
  })();

  globalForDb.__nutreePgInit = initPromise.catch((error) => {
    globalForDb.__nutreePgInit = undefined;
    throw error;
  });

  return globalForDb.__nutreePgInit;
}

export async function queryDb<T extends QueryResultRow = QueryResultRow>(text: string, values: unknown[] = []) {
  await ensureDatabase();
  return getDbPool().query<T>(text, values);
}

export function mapMenuRow(row: Record<string, unknown>): MenuItem {
  return {
    id: Number(row.id),
    productId: String(row.product_id),
    name: String(row.name),
    category: String(row.category),
    pricePaise: Number(row.price_paise),
    costPaise: Number(row.cost_paise),
    isActive: Number(row.is_active) === 1 || row.is_active === true,
  };
}

export async function getSettings(): Promise<BusinessSettings> {
  const result = await queryDb<Record<string, unknown>>(
    "SELECT * FROM business_settings WHERE id = 1",
  );
  const row = result.rows[0];
  if (!row) throw new Error("Business settings have not been initialized.");

  return {
    restaurantName: String(row.restaurant_name),
    address: String(row.address),
    phone: String(row.phone),
    email: String(row.email),
    gstin: String(row.gstin),
    defaultGstRate: Number(row.default_gst_rate),
    printerWidthMm: Number(row.printer_width_mm),
    currencySymbol: String(row.currency_symbol),
    timezone: String(row.timezone),
  };
}
