CREATE TABLE IF NOT EXISTS menu_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  price_paise INTEGER NOT NULL CHECK(price_paise >= 0),
  cost_paise INTEGER NOT NULL DEFAULT 0 CHECK(cost_paise >= 0),
  is_active SMALLINT NOT NULL DEFAULT 1 CHECK(is_active IN (0,1)),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS bills (
  id TEXT PRIMARY KEY,
  bill_date TEXT NOT NULL,
  daily_number INTEGER NOT NULL,
  created_at TEXT NOT NULL,
  customer_name TEXT,
  customer_phone TEXT,
  payment_method TEXT NOT NULL,
  gst_enabled SMALLINT NOT NULL DEFAULT 0 CHECK(gst_enabled IN (0,1)),
  gst_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
  subtotal_paise INTEGER NOT NULL,
  cgst_paise INTEGER NOT NULL DEFAULT 0,
  sgst_paise INTEGER NOT NULL DEFAULT 0,
  total_paise INTEGER NOT NULL,
  cogs_paise INTEGER NOT NULL DEFAULT 0,
  UNIQUE(bill_date, daily_number)
);

CREATE TABLE IF NOT EXISTS bill_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bill_id TEXT NOT NULL REFERENCES bills(id) ON DELETE CASCADE,
  menu_item_id INTEGER,
  product_id TEXT NOT NULL,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  unit_price_paise INTEGER NOT NULL,
  unit_cost_paise INTEGER NOT NULL DEFAULT 0,
  quantity INTEGER NOT NULL CHECK(quantity > 0),
  line_total_paise INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_bills_date ON bills(bill_date);
CREATE INDEX IF NOT EXISTS idx_bill_items_bill ON bill_items(bill_id);

CREATE TABLE IF NOT EXISTS expenses (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  expense_date TEXT NOT NULL,
  amount_paise INTEGER NOT NULL CHECK(amount_paise > 0),
  note TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_expenses_date ON expenses(expense_date);

CREATE TABLE IF NOT EXISTS business_settings (
  id INTEGER PRIMARY KEY CHECK(id = 1),
  restaurant_name TEXT NOT NULL,
  address TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT NOT NULL,
  gstin TEXT NOT NULL,
  default_gst_rate DOUBLE PRECISION NOT NULL,
  printer_width_mm INTEGER NOT NULL,
  currency_symbol TEXT NOT NULL,
  timezone TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS daily_bill_counters (
  bill_date TEXT PRIMARY KEY,
  last_number INTEGER NOT NULL CHECK(last_number >= 0)
);

CREATE SEQUENCE IF NOT EXISTS menu_product_seq START WITH 1 INCREMENT BY 1;
